source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'activerecord', '~> 7.1', '>= 7.1.3.4'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.27'
gem 'sqlite3', '~> 1.3', '>= 1.3.6'
gem 'rest-client'
gem 'pry'
gem 'pry-nav'

gem "rake"
